package com.driftrush.game

// Кодування блоків у компактний рядок:
// S = STRAIGHT, W = WIDE_STRAIGHT
// L = TURN_LEFT, R = TURN_RIGHT
// l = SHARP_LEFT, r = SHARP_RIGHT
// Z = ZIGZAG_LEFT, X = ZIGZAG_RIGHT

object LevelData {

    fun decode(s: String): List<TrackBlock> = s.map { c ->
        when (c) {
            'S' -> TrackBlock(BlockType.STRAIGHT)
            'W' -> TrackBlock(BlockType.WIDE_STRAIGHT)
            'L' -> TrackBlock(BlockType.TURN_LEFT)
            'R' -> TrackBlock(BlockType.TURN_RIGHT)
            'l' -> TrackBlock(BlockType.SHARP_LEFT)
            'r' -> TrackBlock(BlockType.SHARP_RIGHT)
            'Z' -> TrackBlock(BlockType.ZIGZAG_LEFT)
            'X' -> TrackBlock(BlockType.ZIGZAG_RIGHT)
            else -> TrackBlock(BlockType.STRAIGHT)
        }
    }

    // Рівні 1-10: короткі, навчальні (8-12 блоків)
    // Рівні 11-50: середні (13-20 блоків)
    // Рівні 51-150: довгі (21-30 блоків)
    // Рівні 151-300: складні (25-35 блоків)
    // Рівні 301-500: дуже складні (30-40 блоків)

    val LEVELS = listOf(
        // === РІВНІ 1-10: Короткі, легкі ===
        "WWWSSSWWW",                          // 1 - навчальний (окремо обробляється)
        "WWSLSWWS",                           // 2
        "SSRWWRSS",                           // 3
        "WSLWWRWS",                           // 4
        "SSSLWWWS",                           // 5
        "WWRSSSLW",                           // 6
        "SLWWWRSS",                           // 7
        "WWSRLWWS",                           // 8
        "SSRWLWSS",                           // 9
        "WSLRWRWS",                           // 10
        // === РІВНІ 11-20 ===
        "SSLWWRSWLS",                         // 11
        "WWRLSSRLWW",                         // 12
        "SSRWSLWRSS",                         // 13
        "WLSWWSRWLS",                         // 14
        "SRLWWSLRSS",                         // 15
        "WWSLRWWRLS",                         // 16
        "SSRWLSWRSS",                         // 17
        "WLSRWWSLWS",                         // 18
        "SSRLWWRLSS",                         // 19
        "WWSLWRWLSS",                         // 20
        // === РІВНІ 21-30 ===
        "SSLWWRSZXSS",                        // 21
        "WWRLZXWWRLS",                        // 22
        "SSRWZLWRXSS",                        // 23
        "WLZXWWSRLWS",                        // 24
        "SSRLZWWXRSS",                        // 25
        "WWZXSLRWWLS",                        // 26
        "SSRZWLXWRSS",                        // 27
        "WLWZXRWSLWS",                        // 28
        "SSRLWZXRLSS",                        // 29
        "WWZXLWRWLSS",                        // 30
        // === РІВНІ 31-40 ===
        "SSLWWRZXSLSS",                       // 31
        "WWRLZXWRLWSS",                       // 32
        "SSRWZXLWRXSS",                       // 33
        "WLZXWWSRLWSS",                       // 34
        "SSRLZWWXRLSS",                       // 35
        "WWZXSLRWWLSS",                       // 36
        "SSRZWLXWRWSS",                       // 37
        "WLWZXRWSLRSS",                       // 38
        "SSRLWZXRLWSS",                       // 39
        "WWZXLWRWLRSS",                       // 40
        // === РІВНІ 41-50 ===
        "SSLWWRZXSLlSS",                      // 41
        "WWRLZXWRLrWSS",                      // 42
        "SSRWZXLWRXlSS",                      // 43
        "WLZXWWSRLWrSS",                      // 44
        "SSRLZWWXRLlSS",                      // 45
        "WWZXSLRWWLrSS",                      // 46
        "SSRZWLXWRWlSS",                      // 47
        "WLWZXRWSLRrSS",                      // 48
        "SSRLWZXRLWlSS",                      // 49
        "WWZXLWRWLRrSS",                      // 50
        // === РІВНІ 51-60 ===
        "SSLWRZXlrSLSSR",                     // 51
        "WWRLZXlrWRLWSS",                     // 52
        "SSRWZXlrLWRXSS",                     // 53
        "WLZXlrWWSRLWSS",                     // 54
        "SSRLZXlrWXRLSS",                     // 55
        "WWZXlrSLRWWLSS",                     // 56
        "SSRZXlrWLXWRSS",                     // 57
        "WLWZXlrRWSLRSS",                     // 58
        "SSRLWZXlrRLWSS",                     // 59
        "WWZXlrLWRWLRSS",                     // 60
        // === РІВНІ 61-80 ===
        "SSLWRZXlrSLSSRW",                    // 61
        "WWRLZXlrWRLWSSS",                    // 62
        "SSRWZXlrLWRXSSW",                    // 63
        "WLZXlrWWSRLWSSS",                    // 64
        "SSRLZXlrWXRLSSW",                    // 65
        "WWZXlrSLRWWLSSS",                    // 66
        "SSRZXlrWLXWRSSW",                    // 67
        "WLWZXlrRWSLRSSS",                    // 68
        "SSRLWZXlrRLWSSW",                    // 69
        "WWZXlrLWRWLRSSS",                    // 70
        "SSLWRZXlrSLSSRWS",                   // 71
        "WWRLZXlrWRLWSSSS",                   // 72
        "SSRWZXlrLWRXSSWS",                   // 73
        "WLZXlrWWSRLWSSSS",                   // 74
        "SSRLZXlrWXRLSSWS",                   // 75
        "WWZXlrSLRWWLSSSS",                   // 76
        "SSRZXlrWLXWRSSWS",                   // 77
        "WLWZXlrRWSLRSSSS",                   // 78
        "SSRLWZXlrRLWSSWS",                   // 79
        "WWZXlrLWRWLRSSSS",                   // 80
        // === РІВНІ 81-100 ===
        "SSLWRZXlrSLSSRWSZ",                  // 81
        "WWRLZXlrWRLWSSSZX",                  // 82
        "SSRWZXlrLWRXSSWSZ",                  // 83
        "WLZXlrWWSRLWSSSZX",                  // 84
        "SSRLZXlrWXRLSSWSZ",                  // 85
        "WWZXlrSLRWWLSSZXS",                  // 86
        "SSRZXlrWLXWRSSWSZ",                  // 87
        "WLWZXlrRWSLRSSZXS",                  // 88
        "SSRLWZXlrRLWSSZXW",                  // 89
        "WWZXlrLWRWLRSSZXS",                  // 90
        "SSLWRZXlrSLSSRWSZX",                 // 91
        "WWRLZXlrWRLWSSSZXL",                 // 92
        "SSRWZXlrLWRXSSWSZX",                 // 93
        "WLZXlrWWSRLWSSSZXR",                 // 94
        "SSRLZXlrWXRLSSWSZX",                 // 95
        "WWZXlrSLRWWLSSZXSL",                 // 96
        "SSRZXlrWLXWRSSWSZX",                 // 97
        "WLWZXlrRWSLRSSZXSR",                 // 98
        "SSRLWZXlrRLWSSZXWL",                 // 99
        "WWZXlrLWRWLRSSZXSR",                 // 100
        // === РІВНІ 101-150 ===
        "SSLWRZXlrSLSSRWSZXL",                // 101
        "WWRLZXlrWRLWSSSZXLR",                // 102
        "SSRWZXlrLWRXSSWSZXL",                // 103
        "WLZXlrWWSRLWSSSZXRL",                // 104
        "SSRLZXlrWXRLSSWSZXL",                // 105
        "WWZXlrSLRWWLSSZXSLR",                // 106
        "SSRZXlrWLXWRSSWSZXL",                // 107
        "WLWZXlrRWSLRSSZXSRL",                // 108
        "SSRLWZXlrRLWSSZXWLR",                // 109
        "WWZXlrLWRWLRSSZXSRL",                // 110
        "SSLWRZXlrSLSSRWSZXLR",               // 111
        "WWRLZXlrWRLWSSSZXLRS",               // 112
        "SSRWZXlrLWRXSSWSZXLS",               // 113
        "WLZXlrWWSRLWSSSZXRLS",               // 114
        "SSRLZXlrWXRLSSWSZXLS",               // 115
        "WWZXlrSLRWWLSSZXSLRS",               // 116
        "SSRZXlrWLXWRSSWSZXLS",               // 117
        "WLWZXlrRWSLRSSZXSRLS",               // 118
        "SSRLWZXlrRLWSSZXWLRS",               // 119
        "WWZXlrLWRWLRSSZXSRLS",               // 120
        "SSLWRlrZXSLSSRWSZXLRS",              // 121
        "WWRLlrZXWRLWSSSZXLRSW",              // 122
        "SSRWlrZXLWRXSSWSZXLSW",              // 123
        "WLZXlrWWSRLWSSSZXRLSW",              // 124
        "SSRLlrZXWXRLSSWSZXLSW",              // 125
        "WWZXlrSLRWWLSSZXSLRSW",              // 126
        "SSRZlrXWLXWRSSWSZXLSW",              // 127
        "WLWZXlrRWSLRSSZXSRLSW",              // 128
        "SSRLWZXlrRLWSSZXWLRSW",              // 129
        "WWZXlrLWRWLRSSZXSRLSW",              // 130
        "SSLWRlrZXSLSSRWSZXLRSWZ",            // 131
        "WWRLlrZXWRLWSSSZXLRSWZX",            // 132
        "SSRWlrZXLWRXSSWSZXLSWZX",            // 133
        "WLZXlrWWSRLWSSSZXRLSWZX",            // 134
        "SSRLlrZXWXRLSSWSZXLSWZX",            // 135
        "WWZXlrSLRWWLSSZXSLRSWZX",            // 136
        "SSRZlrXWLXWRSSWSZXLSWZX",            // 137
        "WLWZXlrRWSLRSSZXSRLSWZX",            // 138
        "SSRLWZXlrRLWSSZXWLRSWZX",            // 139
        "WWZXlrLWRWLRSSZXSRLSWZX",            // 140
        "SSLWRlrZXSLSSRWSZXLRSWZXl",          // 141
        "WWRLlrZXWRLWSSSZXLRSWZXlr",          // 142
        "SSRWlrZXLWRXSSWSZXLSWZXlr",          // 143
        "WLZXlrWWSRLWSSSZXRLSWZXlr",          // 144
        "SSRLlrZXWXRLSSWSZXLSWZXlr",          // 145
        "WWZXlrSLRWWLSSZXSLRSWZXlr",          // 146
        "SSRZlrXWLXWRSSWSZXLSWZXlr",          // 147
        "WLWZXlrRWSLRSSZXSRLSWZXlr",          // 148
        "SSRLWZXlrRLWSSZXWLRSWZXlr",          // 149
        "WWZXlrLWRWLRSSZXSRLSWZXlr",          // 150
        // === РІВНІ 151-200 ===
        "SSLWRlrZXSLSSRWSZXLRSWZXlrL",        // 151
        "WWRLlrZXWRLWSSSZXLRSWZXlrRL",        // 152
        "SSRWlrZXLWRXSSWSZXLSWZXlrSL",        // 153
        "WLZXlrWWSRLWSSSZXRLSWZXlrRW",        // 154
        "SSRLlrZXWXRLSSWSZXLSWZXlrLS",        // 155
        "WWZXlrSLRWWLSSZXSLRSWZXlrRS",        // 156
        "SSRZlrXWLXWRSSWSZXLSWZXlrLW",        // 157
        "WLWZXlrRWSLRSSZXSRLSWZXlrRL",        // 158
        "SSRLWZXlrRLWSSZXWLRSWZXlrLR",        // 159
        "WWZXlrLWRWLRSSZXSRLSWZXlrSL",        // 160
        "SSLWRlrZXSLSSRWSZXLRSWZXlrLRL",      // 161
        "WWRLlrZXWRLWSSSZXLRSWZXlrRLR",       // 162
        "SSRWlrZXLWRXSSWSZXLSWZXlrSLR",       // 163
        "WLZXlrWWSRLWSSSZXRLSWZXlrRWL",       // 164
        "SSRLlrZXWXRLSSWSZXLSWZXlrLSR",       // 165
        "WWZXlrSLRWWLSSZXSLRSWZXlrRSL",       // 166
        "SSRZlrXWLXWRSSWSZXLSWZXlrLWR",       // 167
        "WLWZXlrRWSLRSSZXSRLSWZXlrRLS",       // 168
        "SSRLWZXlrRLWSSZXWLRSWZXlrLRS",       // 169
        "WWZXlrLWRWLRSSZXSRLSWZXlrSLR",       // 170
        "SSLlrWRZXSLSSRWSZXLRSWZXlrLRL",      // 171
        "WWlrRLZXWRLWSSSZXLRSWZXlrRLRS",      // 172
        "SSlrRWZXLWRXSSWSZXLSWZXlrSLRS",      // 173
        "WlrLZXWWSRLWSSSZXRLSWZXlrRWLS",      // 174
        "SSlrRLZXWXRLSSWSZXLSWZXlrLSRS",      // 175
        "WWlrZXSLRWWLSSZXSLRSWZXlrRSLS",      // 176
        "SSlrRZXWLXWRSSWSZXLSWZXlrLWRS",      // 177
        "WlrLWZXRWSLRSSZXSRLSWZXlrRLSR",      // 178
        "SSlrRLWZXRLWSSZXWLRSWZXlrLRSL",      // 179
        "WWlrZXLWRWLRSSZXSRLSWZXlrSLRL",      // 180
        "SSLlrWRZXSLSSRWSZXLRSWZXlrLRLS",     // 181
        "WWlrRLZXWRLWSSSZXLRSWZXlrRLRSW",     // 182
        "SSlrRWZXLWRXSSWSZXLSWZXlrSLRSW",     // 183
        "WlrLZXWWSRLWSSSZXRLSWZXlrRWLSW",     // 184
        "SSlrRLZXWXRLSSWSZXLSWZXlrLSRSW",     // 185
        "WWlrZXSLRWWLSSZXSLRSWZXlrRSLSW",     // 186
        "SSlrRZXWLXWRSSWSZXLSWZXlrLWRSW",     // 187
        "WlrLWZXRWSLRSSZXSRLSWZXlrRLSRW",     // 188
        "SSlrRLWZXRLWSSZXWLRSWZXlrLRSLW",     // 189
        "WWlrZXLWRWLRSSZXSRLSWZXlrSLRLS",     // 190
        "SSLlrWRZXSLSSRWSZXLRSWZXlrLRLSZ",    // 191
        "WWlrRLZXWRLWSSSZXLRSWZXlrRLRSZX",    // 192
        "SSlrRWZXLWRXSSWSZXLSWZXlrSLRSZX",    // 193
        "WlrLZXWWSRLWSSSZXRLSWZXlrRWLSZX",    // 194
        "SSlrRLZXWXRLSSWSZXLSWZXlrLSRSZX",    // 195
        "WWlrZXSLRWWLSSZXSLRSWZXlrRSLSZX",    // 196
        "SSlrRZXWLXWRSSWSZXLSWZXlrLWRSZX",    // 197
        "WlrLWZXRWSLRSSZXSRLSWZXlrRLSRZX",    // 198
        "SSlrRLWZXRLWSSZXWLRSWZXlrLRSLZX",    // 199
        "WWlrZXLWRWLRSSZXSRLSWZXlrSLRLZX",    // 200
        // === РІВНІ 201-300 (складніші) ===
        "SSLlrWRZXlrSLRWSZXLRSWlrZXLRL",      // 201
        "WWlrRLZXlrWRLZXLRSWlrZXRLRS",        // 202
        "SSlrRWZXlrLRXZXLSWlrZXSLRS",         // 203
        "WlrLZXlrWSRLZXRLSWlrZXRWLS",         // 204
        "SSlrRLZXlrXRLZXLSWlrZXLSRS",         // 205
        "WWlrZXlrLRWLZXSLRSWlrZXRSLS",        // 206
        "SSlrRZXlrLXRZXLSWlrZXLWRS",          // 207
        "WlrLWZXlrRLRZXSRLSWlrZXRLSR",        // 208
        "SSlrRLWZXlrRLZXWLRSWlrZXLRSL",       // 209
        "WWlrZXlrLRLRZXSRLSWlrZXSLRL",        // 210
        "SSLlrWRZXlrSLRWSZXLRSWlrZXLRLS",     // 211
        "WWlrRLZXlrWRLZXLRSWlrZXRLRSW",       // 212
        "SSlrRWZXlrLRXZXLSWlrZXSLRSW",        // 213
        "WlrLZXlrWSRLZXRLSWlrZXRWLSW",        // 214
        "SSlrRLZXlrXRLZXLSWlrZXLSRSW",        // 215
        "WWlrZXlrLRWLZXSLRSWlrZXRSLSW",       // 216
        "SSlrRZXlrLXRZXLSWlrZXLWRSW",         // 217
        "WlrLWZXlrRLRZXSRLSWlrZXRLSRW",       // 218
        "SSlrRLWZXlrRLZXWLRSWlrZXLRSLW",      // 219
        "WWlrZXlrLRLRZXSRLSWlrZXSLRLS",       // 220
        "SSLlrlrWRZXSLRWSZXLRSWZXLRLS",       // 221
        "WWlrlrRLZXWRLZXLRSWZXRLRSW",         // 222
        "SSlrlrRWZXLRXZXLSWZXSLRSW",          // 223
        "WlrlrLZXWSRLZXRLSWZXRWLSW",          // 224
        "SSlrlrRLZXXRLZXLSWZXLSRSW",          // 225
        "WWlrlrZXLRWLZXSLRSWZXRSLSW",         // 226
        "SSlrlrRZXLXRZXLSWZXLWRSW",           // 227
        "WlrlrLWZXRLRZXSRLSWZXRLSRW",         // 228
        "SSlrlrRLWZXRLZXWLRSWZXLRSLW",        // 229
        "WWlrlrZXLRLRZXSRLSWZXSLRLS",         // 230
        "SSLlrlrWRZXSLRWSZXLRSWZXLRLSZ",      // 231
        "WWlrlrRLZXWRLZXLRSWZXRLRSWZX",       // 232
        "SSlrlrRWZXLRXZXLSWZXSLRSWZX",        // 233
        "WlrlrLZXWSRLZXRLSWZXRWLSWZX",        // 234
        "SSlrlrRLZXXRLZXLSWZXLSRSWZX",        // 235
        "WWlrlrZXLRWLZXSLRSWZXRSLSWZX",       // 236
        "SSlrlrRZXLXRZXLSWZXLWRSWZX",         // 237
        "WlrlrLWZXRLRZXSRLSWZXRLSRWZX",       // 238
        "SSlrlrRLWZXRLZXWLRSWZXLRSLWZX",      // 239
        "WWlrlrZXLRLRZXSRLSWZXSLRLSZX",       // 240
        "SSLlrlrWRZXlrSLRWSZXLRSWZXLRL",      // 241
        "WWlrlrRLZXlrWRLZXLRSWZXRLRS",        // 242
        "SSlrlrRWZXlrLRXZXLSWZXSLRS",         // 243
        "WlrlrLZXlrWSRLZXRLSWZXRWLS",         // 244
        "SSlrlrRLZXlrXRLZXLSWZXLSRS",         // 245
        "WWlrlrZXlrLRWLZXSLRSWZXRSLS",        // 246
        "SSlrlrRZXlrLXRZXLSWZXLWRS",          // 247
        "WlrlrLWZXlrRLRZXSRLSWZXRLSR",        // 248
        "SSlrlrRLWZXlrRLZXWLRSWZXLRSL",       // 249
        "WWlrlrZXlrLRLRZXSRLSWZXSLRL",        // 250
        "SSLlrlrWRZXlrSLRWSZXLRlrSWZXLRLS",   // 251
        "WWlrlrRLZXlrWRLZXlrLRSWZXRLRSW",     // 252
        "SSlrlrRWZXlrLRXZXlrLSWZXSLRSW",      // 253
        "WlrlrLZXlrWSRLZXlrRLSWZXRWLSW",      // 254
        "SSlrlrRLZXlrXRLZXlrLSWZXLSRSW",      // 255
        "WWlrlrZXlrLRWLZXlrSLRSWZXRSLSW",     // 256
        "SSlrlrRZXlrLXRZXlrLSWZXLWRSW",       // 257
        "WlrlrLWZXlrRLRZXlrSRLSWZXRLSRW",     // 258
        "SSlrlrRLWZXlrRLZXlrWLRSWZXLRSLW",    // 259
        "WWlrlrZXlrLRLRZXlrSRLSWZXSLRLS",     // 260
        "SSLlrlrWRlrZXSLRWSZXLRSWZXLRLS",     // 261
        "WWlrlrRLlrZXWRLZXLRSWZXRLRSW",       // 262
        "SSlrlrRWlrZXLRXZXLSWZXSLRSW",        // 263
        "WlrlrLlrZXWSRLZXRLSWZXRWLSW",        // 264
        "SSlrlrRLlrZXXRLZXLSWZXLSRSW",        // 265
        "WWlrlrZXlrLRWLZXSLRSWZXRSLSW",       // 266
        "SSlrlrRlrZXLXRZXLSWZXLWRSW",         // 267
        "WlrlrLWlrZXRLRZXSRLSWZXRLSRW",       // 268
        "SSlrlrRLWlrZXRLZXWLRSWZXLRSLW",      // 269
        "WWlrlrZXlrLRLRZXSRLSWZXSLRLS",       // 270
        "SSLlrlrWRZXlrSLlrRWSZXLRSWZXLRLS",   // 271
        "WWlrlrRLZXlrWRlrLZXLRSWZXRLRSW",     // 272
        "SSlrlrRWZXlrLRlrXZXLSWZXSLRSW",      // 273
        "WlrlrLZXlrWSRlrLZXRLSWZXRWLSW",      // 274
        "SSlrlrRLZXlrXRlrLZXLSWZXLSRSW",      // 275
        "WWlrlrZXlrLRWlrLZXSLRSWZXRSLSW",     // 276
        "SSlrlrRZXlrLXRlrZXLSWZXLWRSW",       // 277
        "WlrlrLWZXlrRLRlrZXSRLSWZXRLSRW",     // 278
        "SSlrlrRLWZXlrRLlrZXWLRSWZXLRSLW",    // 279
        "WWlrlrZXlrLRLRlrZXSRLSWZXSLRLS",     // 280
        "SSLlrlrWRZXlrSLRWlrSZXLRSWZXLRLS",   // 281
        "WWlrlrRLZXlrWRLZlrXLRSWZXRLRSW",     // 282
        "SSlrlrRWZXlrLRXZlrXLSWZXSLRSW",      // 283
        "WlrlrLZXlrWSRLZlrXRLSWZXRWLSW",      // 284
        "SSlrlrRLZXlrXRLZlrXLSWZXLSRSW",      // 285
        "WWlrlrZXlrLRWLZlrXSLRSWZXRSLSW",     // 286
        "SSlrlrRZXlrLXRZlrXLSWZXLWRSW",       // 287
        "WlrlrLWZXlrRLRZlrXSRLSWZXRLSRW",     // 288
        "SSlrlrRLWZXlrRLZlrXWLRSWZXLRSLW",    // 289
        "WWlrlrZXlrLRLRZlrXSRLSWZXSLRLS",     // 290
        "SSLlrlrWRZXlrSLRWSZlrXLRSWZXLRLS",   // 291
        "WWlrlrRLZXlrWRLZXLlrRSWZXRLRSW",     // 292
        "SSlrlrRWZXlrLRXZXLlrSWZXSLRSW",      // 293
        "WlrlrLZXlrWSRLZXRLlrSWZXRWLSW",      // 294
        "SSlrlrRLZXlrXRLZXLlrSWZXLSRSW",      // 295
        "WWlrlrZXlrLRWLZXSlrRSWZXRSLSW",      // 296
        "SSlrlrRZXlrLXRZXLlrSWZXLWRSW",       // 297
        "WlrlrLWZXlrRLRZXSlrRLSWZXRLSRW",     // 298
        "SSlrlrRLWZXlrRLZXWlrLRSWZXLRSLW",    // 299
        "WWlrlrZXlrLRLRZXSlrRLSWZXSLRLS",     // 300
        // === РІВНІ 301-400 (дуже складні) ===
        "SSLlrlrWRZXlrlrSLRWSZXLRSWZXlrLRLS",     // 301
        "WWlrlrRLZXlrlrWRLZXLRSWZXlrRLRSW",       // 302
        "SSlrlrRWZXlrlrLRXZXLSWZXlrSLRSW",        // 303
        "WlrlrLZXlrlrWSRLZXRLSWZXlrRWLSW",        // 304
        "SSlrlrRLZXlrlrXRLZXLSWZXlrLSRSW",        // 305
        "WWlrlrZXlrlrLRWLZXSLRSWZXlrRSLSW",       // 306
        "SSlrlrRZXlrlrLXRZXLSWZXlrLWRSW",         // 307
        "WlrlrLWZXlrlrRLRZXSRLSWZXlrRLSRW",       // 308
        "SSlrlrRLWZXlrlrRLZXWLRSWZXlrLRSLW",      // 309
        "WWlrlrZXlrlrLRLRZXSRLSWZXlrSLRLS",       // 310
        "SSLlrlrlrWRZXSLRWSZXLRSWZXLRLS",         // 311
        "WWlrlrlrRLZXWRLZXLRSWZXRLRSW",           // 312
        "SSlrlrlrRWZXLRXZXLSWZXSLRSW",            // 313
        "WlrlrlrLZXWSRLZXRLSWZXRWLSW",            // 314
        "SSlrlrlrRLZXXRLZXLSWZXLSRSW",            // 315
        "WWlrlrlrZXLRWLZXSLRSWZXRSLSW",           // 316
        "SSlrlrlrRZXLXRZXLSWZXLWRSW",             // 317
        "WlrlrlrLWZXRLRZXSRLSWZXRLSRW",           // 318
        "SSlrlrlrRLWZXRLZXWLRSWZXLRSLW",          // 319
        "WWlrlrlrZXLRLRZXSRLSWZXSLRLS",           // 320
        "SSLlrlrlrWRZXlrSLRWSZXLRSWZXLRLS",       // 321
        "WWlrlrlrRLZXlrWRLZXLRSWZXRLRSW",         // 322
        "SSlrlrlrRWZXlrLRXZXLSWZXSLRSW",          // 323
        "WlrlrlrLZXlrWSRLZXRLSWZXRWLSW",          // 324
        "SSlrlrlrRLZXlrXRLZXLSWZXLSRSW",          // 325
        "WWlrlrlrZXlrLRWLZXSLRSWZXRSLSW",         // 326
        "SSlrlrlrRZXlrLXRZXLSWZXLWRSW",           // 327
        "WlrlrlrLWZXlrRLRZXSRLSWZXRLSRW",         // 328
        "SSlrlrlrRLWZXlrRLZXWLRSWZXLRSLW",        // 329
        "WWlrlrlrZXlrLRLRZXSRLSWZXSLRLS",         // 330
        "SSLlrlrlrWRZXlrlrSLRWSZXLRSWlrZXLRL",    // 331
        "WWlrlrlrRLZXlrlrWRLZXLRSWlrZXRLRS",      // 332
        "SSlrlrlrRWZXlrlrLRXZXLSWlrZXSLRS",       // 333
        "WlrlrlrLZXlrlrWSRLZXRLSWlrZXRWLS",       // 334
        "SSlrlrlrRLZXlrlrXRLZXLSWlrZXLSRS",       // 335
        "WWlrlrlrZXlrlrLRWLZXSLRSWlrZXRSLS",      // 336
        "SSlrlrlrRZXlrlrLXRZXLSWlrZXLWRS",        // 337
        "WlrlrlrLWZXlrlrRLRZXSRLSWlrZXRLSR",      // 338
        "SSlrlrlrRLWZXlrlrRLZXWLRSWlrZXLRSL",     // 339
        "WWlrlrlrZXlrlrLRLRZXSRLSWlrZXSLRL",      // 340
        "SSLlrlrlrWRZXlrlrSLRWSZXlrLRSWZXLRLS",   // 341
        "WWlrlrlrRLZXlrlrWRLZXlrLRSWZXRLRSW",     // 342
        "SSlrlrlrRWZXlrlrLRXZXlrLSWZXSLRSW",      // 343
        "WlrlrlrLZXlrlrWSRLZXlrRLSWZXRWLSW",      // 344
        "SSlrlrlrRLZXlrlrXRLZXlrLSWZXLSRSW",      // 345
        "WWlrlrlrZXlrlrLRWLZXlrSLRSWZXRSLSW",     // 346
        "SSlrlrlrRZXlrlrLXRZXlrLSWZXLWRSW",       // 347
        "WlrlrlrLWZXlrlrRLRZXlrSRLSWZXRLSRW",     // 348
        "SSlrlrlrRLWZXlrlrRLZXlrWLRSWZXLRSLW",    // 349
        "WWlrlrlrZXlrlrLRLRZXlrSRLSWZXSLRLS",     // 350
        "SSLlrlrlrWRlrZXSLRWSZXLRSWZXlrLRLS",     // 351
        "WWlrlrlrRLlrZXWRLZXLRSWZXlrRLRSW",       // 352
        "SSlrlrlrRWlrZXLRXZXLSWZXlrSLRSW",        // 353
        "WlrlrlrLlrZXWSRLZXRLSWZXlrRWLSW",        // 354
        "SSlrlrlrRLlrZXXRLZXLSWZXlrLSRSW",        // 355
        "WWlrlrlrZXlrLRWLZXSLRSWZXlrRSLSW",       // 356
        "SSlrlrlrRlrZXLXRZXLSWZXlrLWRSW",         // 357
        "WlrlrlrLWlrZXRLRZXSRLSWZXlrRLSRW",       // 358
        "SSlrlrlrRLWlrZXRLZXWLRSWZXlrLRSLW",      // 359
        "WWlrlrlrZXlrLRLRZXSRLSWZXlrSLRLS",       // 360
        "SSLlrlrlrWRZXlrlrSLlrRWSZXLRSWZXLRLS",   // 361
        "WWlrlrlrRLZXlrlrWRlrLZXLRSWZXRLRSW",     // 362
        "SSlrlrlrRWZXlrlrLRlrXZXLSWZXSLRSW",      // 363
        "WlrlrlrLZXlrlrWSRlrLZXRLSWZXRWLSW",      // 364
        "SSlrlrlrRLZXlrlrXRlrLZXLSWZXLSRSW",      // 365
        "WWlrlrlrZXlrlrLRWlrLZXSLRSWZXRSLSW",     // 366
        "SSlrlrlrRZXlrlrLXRlrZXLSWZXLWRSW",       // 367
        "WlrlrlrLWZXlrlrRLRlrZXSRLSWZXRLSRW",     // 368
        "SSlrlrlrRLWZXlrlrRLlrZXWLRSWZXLRSLW",    // 369
        "WWlrlrlrZXlrlrLRLRlrZXSRLSWZXSLRLS",     // 370
        "SSLlrlrlrWRZXlrlrSLRWlrSZXLRSWZXLRLS",   // 371
        "WWlrlrlrRLZXlrlrWRLZlrXLRSWZXRLRSW",     // 372
        "SSlrlrlrRWZXlrlrLRXZlrXLSWZXSLRSW",      // 373
        "WlrlrlrLZXlrlrWSRLZlrXRLSWZXRWLSW",      // 374
        "SSlrlrlrRLZXlrlrXRLZlrXLSWZXLSRSW",      // 375
        "WWlrlrlrZXlrlrLRWLZlrXSLRSWZXRSLSW",     // 376
        "SSlrlrlrRZXlrlrLXRZlrXLSWZXLWRSW",       // 377
        "WlrlrlrLWZXlrlrRLRZlrXSRLSWZXRLSRW",     // 378
        "SSlrlrlrRLWZXlrlrRLZlrXWLRSWZXLRSLW",    // 379
        "WWlrlrlrZXlrlrLRLRZlrXSRLSWZXSLRLS",     // 380
        "SSLlrlrlrWRZXlrlrSLRWSZlrXLRSWZXLRLS",   // 381
        "WWlrlrlrRLZXlrlrWRLZXLlrRSWZXRLRSW",     // 382
        "SSlrlrlrRWZXlrlrLRXZXLlrSWZXSLRSW",      // 383
        "WlrlrlrLZXlrlrWSRLZXRLlrSWZXRWLSW",      // 384
        "SSlrlrlrRLZXlrlrXRLZXLlrSWZXLSRSW",      // 385
        "WWlrlrlrZXlrlrLRWLZXSlrRSWZXRSLSW",      // 386
        "SSlrlrlrRZXlrlrLXRZXLlrSWZXLWRSW",       // 387
        "WlrlrlrLWZXlrlrRLRZXSlrRLSWZXRLSRW",     // 388
        "SSlrlrlrRLWZXlrlrRLZXWlrLRSWZXLRSLW",    // 389
        "WWlrlrlrZXlrlrLRLRZXSlrRLSWZXSLRLS",     // 390
        "SSLlrlrlrWRZXlrlrlrSLRWSZXLRSWZXLRLS",   // 391
        "WWlrlrlrRLZXlrlrlrWRLZXLRSWZXRLRSW",     // 392
        "SSlrlrlrRWZXlrlrlrLRXZXLSWZXSLRSW",      // 393
        "WlrlrlrLZXlrlrlrWSRLZXRLSWZXRWLSW",      // 394
        "SSlrlrlrRLZXlrlrlrXRLZXLSWZXLSRSW",      // 395
        "WWlrlrlrZXlrlrlrLRWLZXSLRSWZXRSLSW",     // 396
        "SSlrlrlrRZXlrlrlrLXRZXLSWZXLWRSW",       // 397
        "WlrlrlrLWZXlrlrlrRLRZXSRLSWZXRLSRW",     // 398
        "SSlrlrlrRLWZXlrlrlrRLZXWLRSWZXLRSLW",    // 399
        "WWlrlrlrZXlrlrlrLRLRZXSRLSWZXSLRLS",     // 400
        // === РІВНІ 401-500 (максимальна складність) ===
        "SSLlrlrlrlrWRZXSLRWSZXLRSWZXLRLS",       // 401
        "WWlrlrlrlrRLZXWRLZXLRSWZXRLRSW",         // 402
        "SSlrlrlrlrRWZXLRXZXLSWZXSLRSW",          // 403
        "WlrlrlrlrLZXWSRLZXRLSWZXRWLSW",          // 404
        "SSlrlrlrlrRLZXXRLZXLSWZXLSRSW",          // 405
        "WWlrlrlrlrZXLRWLZXSLRSWZXRSLSW",         // 406
        "SSlrlrlrlrRZXLXRZXLSWZXLWRSW",           // 407
        "WlrlrlrlrLWZXRLRZXSRLSWZXRLSRW",         // 408
        "SSlrlrlrlrRLWZXRLZXWLRSWZXLRSLW",        // 409
        "WWlrlrlrlrZXLRLRZXSRLSWZXSLRLS",         // 410
        "SSLlrlrlrlrWRZXlrSLRWSZXLRSWZXLRLS",     // 411
        "WWlrlrlrlrRLZXlrWRLZXLRSWZXRLRSW",       // 412
        "SSlrlrlrlrRWZXlrLRXZXLSWZXSLRSW",        // 413
        "WlrlrlrlrLZXlrWSRLZXRLSWZXRWLSW",        // 414
        "SSlrlrlrlrRLZXlrXRLZXLSWZXLSRSW",        // 415
        "WWlrlrlrlrZXlrLRWLZXSLRSWZXRSLSW",       // 416
        "SSlrlrlrlrRZXlrLXRZXLSWZXLWRSW",         // 417
        "WlrlrlrlrLWZXlrRLRZXSRLSWZXRLSRW",       // 418
        "SSlrlrlrlrRLWZXlrRLZXWLRSWZXLRSLW",      // 419
        "WWlrlrlrlrZXlrLRLRZXSRLSWZXSLRLS",       // 420
        "SSLlrlrlrlrWRZXlrlrSLRWSZXLRlrSWZXLRLS", // 421
        "WWlrlrlrlrRLZXlrlrWRLZXlrLRSWZXRLRSW",   // 422
        "SSlrlrlrlrRWZXlrlrLRXZXlrLSWZXSLRSW",    // 423
        "WlrlrlrlrLZXlrlrWSRLZXlrRLSWZXRWLSW",    // 424
        "SSlrlrlrlrRLZXlrlrXRLZXlrLSWZXLSRSW",    // 425
        "WWlrlrlrlrZXlrlrLRWLZXlrSLRSWZXRSLSW",   // 426
        "SSlrlrlrlrRZXlrlrLXRZXlrLSWZXLWRSW",     // 427
        "WlrlrlrlrLWZXlrlrRLRZXlrSRLSWZXRLSRW",   // 428
        "SSlrlrlrlrRLWZXlrlrRLZXlrWLRSWZXLRSLW",  // 429
        "WWlrlrlrlrZXlrlrLRLRZXlrSRLSWZXSLRLS",   // 430
        "SSLlrlrlrlrWRlrZXlrSLRWSZXLRSWZXLRLS",   // 431
        "WWlrlrlrlrRLlrZXlrWRLZXLRSWZXRLRSW",     // 432
        "SSlrlrlrlrRWlrZXlrLRXZXLSWZXSLRSW",      // 433
        "WlrlrlrlrLlrZXlrWSRLZXRLSWZXRWLSW",      // 434
        "SSlrlrlrlrRLlrZXlrXRLZXLSWZXLSRSW",      // 435
        "WWlrlrlrlrZXlrlrLRWLZXSLRSWZXRSLSW",     // 436
        "SSlrlrlrlrRlrZXlrLXRZXLSWZXLWRSW",       // 437
        "WlrlrlrlrLWlrZXlrRLRZXSRLSWZXRLSRW",     // 438
        "SSlrlrlrlrRLWlrZXlrRLZXWLRSWZXLRSLW",    // 439
        "WWlrlrlrlrZXlrlrLRLRZXSRLSWZXSLRLS",     // 440
        "SSLlrlrlrlrWRZXlrlrlrSLRWSZXLRSWZXLRL",  // 441
        "WWlrlrlrlrRLZXlrlrlrWRLZXLRSWZXRLRS",    // 442
        "SSlrlrlrlrRWZXlrlrlrLRXZXLSWZXSLRS",     // 443
        "WlrlrlrlrLZXlrlrlrWSRLZXRLSWZXRWLS",     // 444
        "SSlrlrlrlrRLZXlrlrlrXRLZXLSWZXLSRS",     // 445
        "WWlrlrlrlrZXlrlrlrLRWLZXSLRSWZXRSLS",    // 446
        "SSlrlrlrlrRZXlrlrlrLXRZXLSWZXLWRS",      // 447
        "WlrlrlrlrLWZXlrlrlrRLRZXSRLSWZXRLSR",    // 448
        "SSlrlrlrlrRLWZXlrlrlrRLZXWLRSWZXLRSL",   // 449
        "WWlrlrlrlrZXlrlrlrLRLRZXSRLSWZXSLRL",    // 450
        "SSLlrlrlrlrWRZXlrlrlrSLlrRWSZXLRSWZXLRLS",  // 451
        "WWlrlrlrlrRLZXlrlrlrWRlrLZXLRSWZXRLRSW",    // 452
        "SSlrlrlrlrRWZXlrlrlrLRlrXZXLSWZXSLRSW",     // 453
        "WlrlrlrlrLZXlrlrlrWSRlrLZXRLSWZXRWLSW",     // 454
        "SSlrlrlrlrRLZXlrlrlrXRlrLZXLSWZXLSRSW",     // 455
        "WWlrlrlrlrZXlrlrlrLRWlrLZXSLRSWZXRSLSW",    // 456
        "SSlrlrlrlrRZXlrlrlrLXRlrZXLSWZXLWRSW",      // 457
        "WlrlrlrlrLWZXlrlrlrRLRlrZXSRLSWZXRLSRW",    // 458
        "SSlrlrlrlrRLWZXlrlrlrRLlrZXWLRSWZXLRSLW",   // 459
        "WWlrlrlrlrZXlrlrlrLRLRlrZXSRLSWZXSLRLS",    // 460
        "SSLlrlrlrlrWRZXlrlrlrSLRWlrSZXLRSWZXLRLS",  // 461
        "WWlrlrlrlrRLZXlrlrlrWRLZlrXLRSWZXRLRSW",    // 462
        "SSlrlrlrlrRWZXlrlrlrLRXZlrXLSWZXSLRSW",     // 463
        "WlrlrlrlrLZXlrlrlrWSRLZlrXRLSWZXRWLSW",     // 464
        "SSlrlrlrlrRLZXlrlrlrXRLZlrXLSWZXLSRSW",     // 465
        "WWlrlrlrlrZXlrlrlrLRWLZlrXSLRSWZXRSLSW",    // 466
        "SSlrlrlrlrRZXlrlrlrLXRZlrXLSWZXLWRSW",      // 467
        "WlrlrlrlrLWZXlrlrlrRLRZlrXSRLSWZXRLSRW",    // 468
        "SSlrlrlrlrRLWZXlrlrlrRLZlrXWLRSWZXLRSLW",   // 469
        "WWlrlrlrlrZXlrlrlrLRLRZlrXSRLSWZXSLRLS",    // 470
        "SSLlrlrlrlrWRZXlrlrlrSLRWSZlrXLRSWZXLRLS",  // 471
        "WWlrlrlrlrRLZXlrlrlrWRLZXLlrRSWZXRLRSW",    // 472
        "SSlrlrlrlrRWZXlrlrlrLRXZXLlrSWZXSLRSW",     // 473
        "WlrlrlrlrLZXlrlrlrWSRLZXRLlrSWZXRWLSW",     // 474
        "SSlrlrlrlrRLZXlrlrlrXRLZXLlrSWZXLSRSW",     // 475
        "WWlrlrlrlrZXlrlrlrLRWLZXSlrRSWZXRSLSW",     // 476
        "SSlrlrlrlrRZXlrlrlrLXRZXLlrSWZXLWRSW",      // 477
        "WlrlrlrlrLWZXlrlrlrRLRZXSlrRLSWZXRLSRW",    // 478
        "SSlrlrlrlrRLWZXlrlrlrRLZXWlrLRSWZXLRSLW",   // 479
        "WWlrlrlrlrZXlrlrlrLRLRZXSlrRLSWZXSLRLS",    // 480
        "SSLlrlrlrlrWRZXlrlrlrlrSLRWSZXLRSWZXLRLS",  // 481
        "WWlrlrlrlrRLZXlrlrlrlrWRLZXLRSWZXRLRSW",    // 482
        "SSlrlrlrlrRWZXlrlrlrlrLRXZXLSWZXSLRSW",     // 483
        "WlrlrlrlrLZXlrlrlrlrWSRLZXRLSWZXRWLSW",     // 484
        "SSlrlrlrlrRLZXlrlrlrlrXRLZXLSWZXLSRSW",     // 485
        "WWlrlrlrlrZXlrlrlrlrLRWLZXSLRSWZXRSLSW",    // 486
        "SSlrlrlrlrRZXlrlrlrlrLXRZXLSWZXLWRSW",      // 487
        "WlrlrlrlrLWZXlrlrlrlrRLRZXSRLSWZXRLSRW",    // 488
        "SSlrlrlrlrRLWZXlrlrlrlrRLZXWLRSWZXLRSLW",   // 489
        "WWlrlrlrlrZXlrlrlrlrLRLRZXSRLSWZXSLRLS",    // 490
        "SSLlrlrlrlrWRZXlrlrlrlrSLRWSZXLRlrSWZXLRLS",// 491
        "WWlrlrlrlrRLZXlrlrlrlrWRLZXlrLRSWZXRLRSW",  // 492
        "SSlrlrlrlrRWZXlrlrlrlrLRXZXlrLSWZXSLRSW",   // 493
        "WlrlrlrlrLZXlrlrlrlrWSRLZXlrRLSWZXRWLSW",   // 494
        "SSlrlrlrlrRLZXlrlrlrlrXRLZXlrLSWZXLSRSW",   // 495
        "WWlrlrlrlrZXlrlrlrlrLRWLZXlrSLRSWZXRSLSW",  // 496
        "SSlrlrlrlrRZXlrlrlrlrLXRZXlrLSWZXLWRSW",    // 497
        "WlrlrlrlrLWZXlrlrlrlrRLRZXlrSRLSWZXRLSRW",  // 498
        "SSlrlrlrlrRLWZXlrlrlrlrRLZXlrWLRSWZXLRSLW", // 499
        "WWlrlrlrlrZXlrlrlrlrLRLRZXlrSRLSWZXSLRLSZX" // 500
    )

    fun getLevel(index: Int): List<TrackBlock> {
        if (index < 1 || index > LEVELS.size) return decode("WWWSSSWWW")
        return decode(LEVELS[index - 1])
    }

    fun getLevelCount() = LEVELS.size
}
